### ISSUE TITLE
Crash on Android with AdMob mediation

### ISSUE THREAD

**Issue by xfxdev** [AdColony/AdColony-Android-SDK-3#29]
Hi, I use AdColony with AdMob mediation.

```
implementation 'com.adcolony:sdk:3.3.2'
implementation 'com.android.support:support-annotations:27.1.1'
implementation 'com.google.ads.mediation:adcolony:3.3.2.0'
```

This is the Crashlytics report of my App:

Last 7 days
3093  CRASHES
2267  USERS

```
Crash Devices
samsung 59%
HUAWEI 15%
HMD Global 7%
LENOVO 5%
Other… 14%

Crash Operating Systems
7           60%
6           19%
5           9%
8           9%
Other… 3%
```

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.concurrent.ExecutorService.shutdown()' on a null object reference
       at com.adcolony.sdk.ac.b(SourceFile:143)
       at com.adcolony.sdk.ao.b(SourceFile:214)
       at com.adcolony.sdk.ao.run(SourceFile:145)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by akwkong** [comment]
Sorry to hear that your users are experiencing this crash. We will be releasing a fix for this soon.

**Comment by akwkong** [comment]
We just released version 3.3.3 of our Android SDK which should resolve the crashes you are seeing. Could you give it a try when you get a chance?

**Comment by xfxdev** [comment]
Thanks, I'll try and let you know the result.

**Comment by xfxdev** [comment]
Still crash

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.List java.util.concurrent.ExecutorService.shutdownNow()' on a null object reference
       at com.adcolony.sdk.ac.b(SourceFile:151)
       at com.adcolony.sdk.ao.b(SourceFile:214)
       at com.adcolony.sdk.ao.run(SourceFile:145)
       at java.lang.Thread.run(Thread.java:818)

**Comment by akwkong** [comment]
Apologies that it is still crashing for you. We will investigate how to fix this version of the crash.

Could you let us know if the frequency of these crashes on 3.3.3 is the same as when you were using 3.3.2 or if they are reduced at all?

**Comment by xfxdev** [comment]
I only rollout at 25% users in the latest version, and only 5 crash until now.
So the frequency seems quite low:)

**Comment by perrychinn** [comment]
Thank you for your reply!  We will forward your information to our Engineers.  Our team is still analyzing the issue and working on a solution.  We'll keep you updated when a fix becomes available.  Thanks.

**Comment by xfxdev** [comment]
OK Thanks~

**Comment by perrychinn** [comment]
Hi,
Just a quick update, we plan to have an SDK release that fixes this issue around mid-May.  Thanks.

**Comment by cigumo** [comment]
@xfxdev how did the rollout of version 3.3.3 go?
Thanks.

**Comment by xfxdev** [comment]
@cigumo Still dozens of crashes......:(

**Comment by cigumo** [comment]
Thanks @xfxdev 
I had to revert to 3.2.1 because it was killing my crash rate on Google Play.
I'm not using AdMob integration.
More than 60% of all the game crashes with AdColony 3.3.2 are similar to the NullPointerException you mention in sdk.ac.b
```
java.lang.NullPointerException: 
  at com.adcolony.sdk.ac.b (SourceFile:143)
  at com.adcolony.sdk.ao.b (SourceFile:214)
  at com.adcolony.sdk.ao.run (SourceFile:145)
  at java.lang.Thread.run (Thread.java:764)
```

Crashlytics adds more information:
```
Attempt to invoke interface method 'void java.util.concurrent.ExecutorService.shutdown()' on a null object reference
com.adcolony.sdk.ac.b
```
It also says that 82% of these crashes are when the app is in the background. 

I disabled AdColony in the app (because I have remote config) but still crashes, so it is not related to showing ads, but something it is doing in the background. 

I hope they fix this in the next release. It's really bad.

**Comment by xfxdev** [comment]
yes its really bad
@akwkong said they will release a new version around mid-May, hope they can fix it in this version.

**Comment by pchinn** [comment]
Hi,
We appreciate your patience.  We released our SDK v3.3.4 today.  It contains a fix for the crash you are seeing.  Please upgrade your app to our v3.3.4.  Thanks.

**Comment by xfxdev** [comment]
@pchinn Thanks, I'll try~

**Comment by obaidahmed234** [comment]
@pchinn with SDK v3.3.4 We're also facing following ANR. 

`"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x75290560 self=0xf1004400
  | sysTid=18619 nice=-10 cgrp=default sched=0/0 handle=0xf3cc7538
  | state=S schedstat=( 2772082720 887863427 4917 ) utm=201 stm=76 core=1 HZ=100
  | stack=0xff065000-0xff067000 stackSize=8MB
  | held mutexes=
 
  #00  pc 0000000000048358  /system/lib/libc.so (__ioctl+8)
 
  #01  pc 000000000001ab0f  /system/lib/libc.so (ioctl+38)
 
  #02  pc 000000000003cc87  /system/lib/libbinder.so (_ZN7android14IPCThreadState14talkWithDriverEb+202)
 
  #03  pc 000000000003d6cf  /system/lib/libbinder.so (_ZN7android14IPCThreadState15waitForResponseEPNS_6ParcelEPi+246)
 
  #04  pc 000000000003656d  /system/lib/libbinder.so (_ZN7android8BpBinder8transactEjRKNS_6ParcelEPS1_j+36)
 
  #05  pc 000000000008c571  /system/lib/libmedia.so (???)
 
  #06  pc 0000000000084d0d  /system/lib/libmedia.so (_ZN7android11MediaPlayer13setDataSourceEixx+68)
 
  #07  pc 000000000002bc7f  /system/lib/libmedia_jni.so (???)
 
  #08  pc 0000000000a67367  /data/dalvik-cache/arm/system@framework@boot.oat (Java_android_media_MediaPlayer__1setDataSource__Ljava_io_FileDescriptor_2JJ+130)
 
  at android.media.MediaPlayer._setDataSource (Native method)
 
  at android.media.MediaPlayer.setDataSource (MediaPlayer.java:1161)
 
  at android.media.MediaPlayer.setDataSource (MediaPlayer.java:1144)
 
  at com.adcolony.sdk.ax.b (SourceFile:162)
 
  at com.adcolony.sdk.c.g (SourceFile:426)
 
  at com.adcolony.sdk.c$1.a (SourceFile:146)
 
  at com.adcolony.sdk.ag.a (SourceFile:188)
- locked <0x06c20e0c> (a java.util.HashMap)
 
  at com.adcolony.sdk.ag$2.run (SourceFile:157)
 
  at android.os.Handler.handleCallback (Handler.java:754)
 
  at android.os.Handler.dispatchMessage (Handler.java:95)
 
  at android.os.Looper.loop (Looper.java:163)
 
  at android.app.ActivityThread.main (ActivityThread.java:6205)
 
  at java.lang.reflect.Method.invoke! (Native method)
 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:904)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:794)`

**Comment by pchinn** [comment]
Hi @obaidahmed234   Is your app using our native Android SDK or through third party mediation/Unity plugin? Does this crash occur on specific device models or OS versions?  Thanks.

**Comment by pchinn** [comment]
Hi @obaidahmed234   Also, it would be easier if you sent your response directly to us via support@adcolony.com.   This will help us investigate your issue quicker.  Thank you.

**Comment by xfxdev** [comment]
Still crash with SDK v3.3.4 :( @akwkong @pchinn 

```
Fatal Exception: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@42625798 rejected from java.util.concurrent.ThreadPoolExecutor@42acb968[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 17]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1334)
       at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:81)
       at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:593)
       at com.adcolony.sdk.ac.a(SourceFile:66)
       at com.adcolony.sdk.ac.a(SourceFile:60)
       at com.adcolony.sdk.aa.a(SourceFile:22)
       at com.adcolony.sdk.aa.a(SourceFile:3)
       at com.adcolony.sdk.aa$a.a(SourceFile:71)
       at com.adcolony.sdk.p.run(SourceFile:111)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by brittmullen** [comment]
@xfxdev I've created a separate issue for the new crash you've reported #37
